# Guevara-Heun meeting notes


## 8 December 2023

### Previous action items:

- [ ] MKH: Aggregate Transfers to Oil refineries in ITA for 2000-2008
- [ ] MKH: Aggregate Solar, Wind, Hydro, and Geothermal to Renewable electricity for 2015 for all countries
- [ ] MKH: Aggregate Coke ovens, Blast furnaces, and Gas works to "Iron industry" for ITA for all years
- [ ] ZG: Suggest more aggregations using the new format defined for the pipeline

Discussion notes:


### New action items:





## 13 October 2023

### Previous action items:

- [x] MKH: Combine "For blended natural gas" and "Natural gas extraction" in every country.
- [x] MKH: Build a system to to enable aggregations in arbitrary countries and years.
- [x] MKH: Write ECC matrices for ITA in 2000 and 2018 to an Excel file
           for inspection at next meeting.
- [x] MKH: Build a file in our GitHub repository to assist with action items. (This file!)

Discussion notes:

* We need to figure out how to deal with Losses
    - Add to U_EIOU (and U)
    - Subtract from V
* We need to figure out how to deal with Transfers.
  Want a algorithm that tells how to deal with lossses
  in a general way.
  
### New action items

- [ ] MKH: Aggregate Transfers to Oil refineries in ITA for 2000-2008
- [ ] MKH: Aggregate Solar, Wind, Hydro, and Geothermal to Renewable electricity for 2015 for all countries
- [ ] MKH: Aggregate Coke ovens, Blast furnaces, and Gas works to "Iron industry" for ITA for all years
- [ ] ZG: Suggest more aggregations using the new format defined for the pipeline


## 22 September 2023

### Previous action items:

- [x] MKH: Create reports of Industry efficiencies. 
           See /OutputData/Reports/IEA eta_i reports folder in Dropbox.
- [x] ZG: Review efficiency data after MKH creates.

### New action items:

- [ ] MKH: Combine "For blended natural gas" and "Natural gas extraction" in every country.
- [ ] MKH: Build a system to to enable aggregations in arbitrary countries and years.
- [ ] MKH: Write ECC matrices for ITA in 2000 and 2018 to an Excel file
           for inspection at next meeting.
- [ ] MKH: Build a file in our GitHub repository to assist with action items. (This file!)


## 8 September 2023

### New action items:

- [ ] MKH: Create reports of Industry efficiencies.
- [ ] ZG: Review efficiency data after MKH creates.
